version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URL=mongodb://dbuser:secretpassword@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: